"""Initial models: users, sessions, positions, arrets

Revision ID: 6fc571153c0e
Revises: 
Create Date: 2026-08-03 14:21:14.283986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc571153c0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('superviseur', 'manager_regional', 'manager_national', 'admin', name='role_enum'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('statut_compte', sa.Enum('actif', 'inactif', name='statut_compte_enum'), nullable=True),
    sa.Column('photo_profil', sa.String(length=255), nullable=True),
    sa.Column('derniere_maj', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('sessions_partage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_session', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.DateTime(), nullable=False),
    sa.Column('heure_fin', sa.DateTime(), nullable=True),
    sa.Column('distance_totale', sa.Float(), nullable=True),
    sa.Column('duree_totale', sa.Integer(), nullable=True),
    sa.Column('vitesse_max', sa.Float(), nullable=True),
    sa.Column('statut_session', sa.Enum('active', 'terminee', name='statut_session_enum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_arret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('heure_arrivee', sa.DateTime(), nullable=False),
    sa.Column('heure_depart', sa.DateTime(), nullable=True),
    sa.Column('duree_arret', sa.Integer(), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_partage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions_gps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('vitesse', sa.Float(), nullable=True),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_partage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions_gps')
    op.drop_table('points_arret')
    op.drop_table('sessions_partage')
    op.drop_table('users')
    # ### end Alembic commands ###
